---
- name: Install Apache2
  sudo: yes
  apt: name=apache2 state=present

- name: enabled mod_rewrite
  sudo: yes
  apache2_module: name=rewrite state=present

- name: enabled mod_headers
  sudo: yes
  apache2_module: name=headers state=present

- name: remove all default vhosts
  file: state=absent path=/etc/apache2/sites-enabled
  
- file: state=directory path=/etc/apache2/sites-enabled

- name: Create apache2.conf
  sudo: yes
  template: src=default.tpl dest=/etc/apache2/sites-enabled/default.conf
  notify: restart apache
