---
- name: Install PHP packages
  sudo: yes
  apt:  package={{ item.package }} state=latest
  with_items: php_packages

- name: Enable PHP packages
  sudo: yes
  command: /usr/sbin/{{ php_version }}enmod {{ item.name }} creates=/etc/{{ php_version }}/cli/conf.d/20-{{ item.name }}.ini
  with_items: php_packages

- name: Install PHP extensions
  sudo: yes
  shell: echo "\n" | /usr/bin/pecl install {{ item.package }} creates=/usr/lib/{{ php_version }}/20121212/{{ item.name }}.so
  with_items: php_extensions

- name: Configure PHP extensions
  sudo: yes
  template: src=extension.tpl dest=/etc/{{ php_version }}/mods-available/{{ item.name }}.ini
  with_items: php_extensions

- name: Enable PHP extensions
  sudo: yes
  command: /usr/sbin/{{ php_version }}enmod {{ item.name }} creates=/etc/{{ php_version }}/cli/conf.d/20-{{ item.name }}.ini
  with_items: php_extensions

- name: notify restart php-fpm
  debug: "notify restart php-fpm"
  notify: restart php-fpm
  when: use_php_fpm
