---
- hosts: all
  sudo:  true
  vars:
    doc_root: /var/www/web
    php_ppa: php5
    php_version: php5
    sys_packages:
      - mcrypt
      - vim
    php_packages:
      - { name: dev, package: "{{php_version}}"-dev }
      - { name: pear, package: php-pear }
      - { name: xdebug, package: "{{php_version}}"-xdebug }
      - { name: curl, package: "{{php_version}}"-curl }
      - { name: mcrypt, package: "{{php_version}}"-mcrypt }
      - { name: mysql, package: "{{php_version}}"-mysql }
      - { name: redis, package: "{{php_version}}"-redis }
      - { name: apc, package: php-apc }
      - { name: memcached, package: "{{php_version}}"-memcached }
      - { name: sqlite, package: "{{php_version}}"-sqlite }
      - { name: gd, package: "{{php_version}}"-gd }
    php_extensions:
      - { name: "jsmin", package: "pecl.php.net/jsmin-beta" }
      - { name: "mongo", package: "pecl.php.net/mongo" }
      - { name: "xhprof", package: "pecl.php.net/xhprof-beta" }
    nodejs:
      version: _5.x
      packages: [casperjs, phantomjs, bower, gulp]
  roles:
    - init
    - apache
    - php-apache
    - php-cli
    - php-common
    - composer
    - phpunit
    - mysql
    - git
    - curl
    - wget
    - redis
    - memcached
    - nodejs
